#version: "2.29.6"

services:
  mini_serv:
    image: server42:v1
    build: ../V  
    container_name: server60

  my_nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - 80:8080  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
